# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c7f3d0f8c3ef64f452071a4ddb6909625ca08935e2408aa6f20143a103e6e214506310d44de0da49d09e23b71905910be2c885d56c1819de24d3982b22aadef

test:
  secret_key_base: 031999970b4b8d292960f3708f128521408c90e4ca645c949ec858beb4ec3bb6c88fe76113815c523e7a4b86f79158ceb70fd9d3eb14411baf40c4b748966db8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
